// Export service for generating various output formats
import { Pin, Package } from '@/types';

export class ExportService {
  /**
   * Export pins to Xilinx Design Constraints (XDC) format
   */
  static exportToXDC(pins: Pin[], packageData: Package | null): string {
    const assignedPins = pins.filter(pin => pin.isAssigned && pin.signalName.trim() !== '');
    
    const header = [
      `# Xilinx Design Constraints (XDC) File`,
      `# Generated by FPGA Pin Planner`,
      `# Date: ${new Date().toLocaleDateString()}`,
      `# Device: ${packageData?.device || 'Unknown'}`,
      `# Package: ${packageData?.packageType || 'Unknown'}`,
      `#`,
      `# Total pins assigned: ${assignedPins.length}`,
      ``,
    ].join('\n');

    const constraints = assignedPins.map(pin => {
      const lines = [];
      
      // Pin location constraint
      lines.push(`set_property PACKAGE_PIN ${pin.pinNumber} [get_ports ${pin.signalName}]`);
      
      // I/O standard constraint (if available)
      if (pin.voltage) {
        const iostandard = pin.voltage === '3.3V' ? 'LVCMOS33' : 
                          pin.voltage === '1.8V' ? 'LVCMOS18' :
                          pin.voltage === '2.5V' ? 'LVCMOS25' : 'LVCMOS33';
        lines.push(`set_property IOSTANDARD ${iostandard} [get_ports ${pin.signalName}]`);
      }
      
      // Drive strength for outputs (if direction is available)
      if (pin.direction === 'Output' || pin.direction === 'InOut') {
        lines.push(`set_property DRIVE 12 [get_ports ${pin.signalName}]`);
      }
      
      return lines.join('\n');
    }).join('\n\n');

    return header + constraints;
  }

  /**
   * Export pins to CSV format
   */
  static exportToCSV(pins: Pin[]): string {
    const headers = [
      'Pin Number',
      'Pin Name', 
      'Signal Name',
      'Direction',
      'Pin Type',
      'Voltage',
      'Bank',
      'I/O Type',
      'Is Assigned'
    ];

    const rows = pins.map(pin => [
      pin.pinNumber,
      pin.pinName,
      pin.signalName || '',
      pin.direction,
      pin.pinType,
      pin.voltage,
      pin.bank || '',
      pin.ioType || '',
      pin.isAssigned ? 'Yes' : 'No'
    ]);

    return [headers, ...rows]
      .map(row => row.map(cell => `"${cell}"`).join(','))
      .join('\n');
  }

  /**
   * Export pin assignment report
   */
  static exportReport(pins: Pin[], packageData: Package | null): string {
    const assignedPins = pins.filter(p => p.isAssigned);
    const unassignedPins = pins.filter(p => !p.isAssigned);
    
    const bankStats = new Map<string, {assigned: number, total: number}>();
    pins.forEach(pin => {
      const bank = pin.bank || 'Unknown';
      if (!bankStats.has(bank)) {
        bankStats.set(bank, {assigned: 0, total: 0});
      }
      const stats = bankStats.get(bank)!;
      stats.total++;
      if (pin.isAssigned) stats.assigned++;
    });

    const report = [
      '# FPGA Pin Assignment Report',
      `# Generated: ${new Date().toLocaleString()}`,
      `# Device: ${packageData?.device || 'Unknown'}`,
      `# Package: ${packageData?.packageType || 'Unknown'}`,
      '',
      '## Summary',
      `- Total Pins: ${pins.length}`,
      `- Assigned Pins: ${assignedPins.length}`,
      `- Unassigned Pins: ${unassignedPins.length}`,
      `- Assignment Rate: ${((assignedPins.length / pins.length) * 100).toFixed(1)}%`,
      '',
      '## Bank Statistics',
      ...Array.from(bankStats.entries()).map(([bank, stats]) => 
        `- Bank ${bank}: ${stats.assigned}/${stats.total} (${((stats.assigned/stats.total)*100).toFixed(1)}%)`
      ),
      '',
      '## Assigned Pins',
      ...assignedPins.map(pin => 
        `${pin.pinNumber.padEnd(8)} | ${pin.signalName.padEnd(20)} | Bank ${(pin.bank || 'N/A').padEnd(3)} | ${pin.pinType}`
      ),
      '',
      '## Pin Type Distribution',
      ...Object.entries(
        pins.reduce((acc, pin) => {
          acc[pin.pinType] = (acc[pin.pinType] || 0) + 1;
          return acc;
        }, {} as Record<string, number>)
      ).map(([type, count]) => `- ${type}: ${count}`)
    ];

    return report.join('\n');
  }

  /**
   * Download file helper
   */
  static downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}
